Feature/validation for snapzones
Innoactive/Basic-Interaction-Component pull request #29
Opened 2020-08-31 07:34 UTC by SimonTheSourcerer

### Description
Adds a basic validator for snapzones, which allows to only snap specific TrainingSceneObjects

### Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

### How Has This Been Tested?
Test it with XR-Interactions

2020-08-31 08:51 UTC, Gusinuhe requested changes

2020-08-31 08:51 UTC, Gusinuhe commented on Runtime/Validation/IsTrainingSceneObjectValidation.cs
> +    public class IsTrainingSceneObjectValidation : Validator
Missing docs

2020-08-31 08:51 UTC, Gusinuhe commented on Runtime/Validation/IsTrainingSceneObjectValidation.cs
> +        public TrainingSceneObject[] AcceptedTrainingSceneObjects = {};
Missing docs.
Is this intended to be visible in the editor? If so, could you add a tooltip?
Is it intended to be public and serialized? Unity automatically serializes public fields.

2020-08-31 08:51 UTC, Gusinuhe commented on Runtime/Validation/Validator.cs
> +    public abstract class Validator : MonoBehaviour
Missing docs

2020-08-31 08:51 UTC, Gusinuhe commented on Runtime/Validation/Validator.cs
> +        public bool IsActive = true;
Is this intended to be public and serialized? 🤔

2020-09-01 09:03 UTC, tomwim approved these changes

2020-09-01 09:15 UTC, Gusinuhe approved these changes

2020-09-01 09:15 UTC, Gusinuhe commented on Runtime/Validation/IsTrainingSceneObjectValidation.cs
> +        private TrainingSceneObject[] acceptedTrainingSceneObjects = {};
Nice to have: tooltip.

2020-09-01 09:42 UTC, Gusinuhe approved these changes

2020-09-01 09:50 UTC, merged