Feature/validation ui trng 1098
Innoactive/Basic-Interaction-Component pull request #33
Opened 2020-10-27 09:35 UTC by SimonTheSourcerer

### Description
Part of https://github.com/Innoactive/Creator/pull/189

2020-10-27 14:33 UTC, Gusinuhe requested changes
Is it `CREATOR_PLUS` or `CREATOR_PRO`? 🤔

2020-10-28 09:04 UTC, SimonTheSourcerer commented
Pro it is !

2020-10-28 09:50 UTC, tomwim submitted a review, later dismissed

2020-10-28 09:53 UTC, tomwim approved these changes

2020-10-28 10:12 UTC, Gusinuhe approved these changes

2020-10-28 12:26 UTC, Maxsiom approved these changes

2020-10-28 16:11 UTC, SimonTheSourcerer commented
/AzurePipelines run

2020-10-28 16:21 UTC, merged