Feature/dynamic rig loading
Innoactive/Basic-Interaction-Component pull request #37
Opened 2021-01-21 09:06 UTC by SimonTheSourcerer

### Description
Allows to add an interaction rig on runtime.

**Test Configuration**:
git clone --single-branch --branch develop git@github.com:Innoactive/Basic-Conditions-And-Behaviors.git Innoactive/Creator/Components/Basic-ConditionsBehaviors
git clone --single-branch --branch feature/dynamic-rig-loading git@github.com:Innoactive/Basic-Interaction-Component.git Innoactive/Creator/Components/Basic-Interaction
git clone --single-branch --branch develop git@github.com:Innoactive/Basic-UI-Component.git Innoactive/Creator/Components/Basic-UI-Components
git clone --single-branch --branch develop git@github.com:Innoactive/TextToSpeech-Component.git Innoactive/Creator/Components/TextToSpeech
git clone --single-branch --branch feature/dynamically-loaded-xr-rigs git@github.com:Innoactive/XR-Interaction-Component.git Innoactive/Creator/Components/XR-Interaction-Component
git clone --single-branch --branch develop git@github.com:Innoactive/Creator.git Innoactive/Creator/Core
git clone --single-branch --branch develop git@github.com:Innoactive/IA-Training-Template.git Innoactive/Creator/IA-Training-Template

2021-01-26 12:19 UTC, Gusinuhe requested changes

2021-01-26 12:19 UTC, Gusinuhe commented on Editor/RigSetup/InteractionFrameworkSceneSetup.cs
> +﻿namespace Innoactive.CreatorEditor.BasicInteraction.RigSetup
<img width="1440" alt="Screenshot 2021-01-26 at 13 13 43" src="https://user-images.githubusercontent.com/6911992/105844147-0ae12000-5fd9-11eb-914e-7a7f1efab371.png">

2021-01-26 15:16 UTC, Gusinuhe commented on Editor/RigSetup/InteractionRigSetupDrawer.cs
> +                if (!canBeUsed)
```suggestion
                if (canBeUsed == false)
```

2021-01-27 14:47 UTC, Gusinuhe commented
Funny log messages are spotted!

![image](https://user-images.githubusercontent.com/6911992/106007688-dba0e080-60b6-11eb-8e0e-44cdda97503b.png)

2021-01-27 15:33 UTC, Gusinuhe submitted a review, later dismissed

2021-01-28 14:32 UTC, Gusinuhe approved these changes

2021-01-29 15:33 UTC, Luphoxa commented
I cloned all the needed components in an existing project and I get the following errors. I had the same problem with another existing project on thursday and asked Gustavo for help, but he was not able to reproduce it. I will try it on Monday with a completely new project and probably ask for dev help on the topic, as this is a real pain ^^'

> Assets\Innoactive\Creator\Components\Basic-UI-Components\Runtime\CourseController\StandaloneMenuHandler.cs(72,25): error CS0234: The type or namespace name 'InputSystem' does not exist in the namespace 'UnityEngine' (are you missing an assembly reference?)

> Assets\Innoactive\Creator\Components\Basic-UI-Components\Runtime\CourseController\StandaloneMenuHandler.cs(72,108): error CS0234: The type or namespace name 'InputSystem' does not exist in the namespace 'UnityEngine' (are you missing an assembly reference?)

2021-02-01 10:59 UTC, merged

2021-02-01 12:57 UTC, Luphoxa commented
I was still testing this, as said in the daily. If you are not sure if I am done testing or have tested this at all, feel free to write me in slack to ask or give me a headsup that I am already testing old news, please. Thanks.