feat: new abstract teleportation simulator TRNG-1453
Innoactive/Basic-Interaction-Component pull request #48
Opened 2021-03-30 22:58 UTC by Gusinuhe

### Description

### Type of change

- [x] New feature (non-breaking change which adds functionality)

### Relates

-

2021-03-31 07:52 UTC, vued requested changes
Basic tests failed. Left test results in slack: https://innoactive.slack.com/archives/C01DU4WGE5Q/p1617176159000800

2021-03-31 17:08 UTC, vued submitted a review, later dismissed
Please check the comments here: https://innoactive.slack.com/archives/C01DU4WGE5Q/p1617210441005800?thread_ts=1617176159.000800&cid=C01DU4WGE5Q
I think they should not block this PR but they should be addressed.

2021-04-06 09:18 UTC, tomwim requested changes

2021-04-06 09:18 UTC, tomwim commented on Runtime/Interaction/TeleportationSimulator.cs
> +    /// Interaction simulator dummy, does nothing beside of warning to there is no concrete implementation of a simulator.
```suggestion
    /// Interaction simulator dummy. Does nothing besides warning that there is no concrete implementation of a <see cref="BaseTeleportationSimulator"/>.
```

2021-04-06 09:53 UTC, tomwim approved these changes

2021-04-06 14:02 UTC, merged